#!/usr/bin/env python3
"""Manage the global Shavian UI Studio taste profile.

The taste profile is a plain-text Markdown file owned by the user that records
their durable design preferences so the workflow learns them over time across
every project.

Safety:
- Writes ONLY inside ~/.claude/shavian-ui-studio/. Never touches anything else.
- No network access.
- `--init` never overwrites an existing profile.
- All edits to the profile content are made by the model through normal file
  editing; this script only bootstraps and reads it transparently.
"""
from __future__ import annotations

import argparse
import datetime as dt
from pathlib import Path
import sys

VERSION = "1.1.0"

EMBEDDED_SEED = """\
<!-- SHAVIAN-UI-STUDIO:TASTE-PROFILE -->
# Personal taste profile

Created with Shavian UI Studio by Shavian Music (@shavianofficial).

This is a durable, cross-project record of your design preferences. It is
plain text, owned by you, stored locally. Edit or delete it freely. The
workflow reads it at the start of a project and refines it (with your
approval) as you approve and reject directions.

## How to read confidence
- LIKELY  — observed once or stated once.
- STRONG  — confirmed across two or more projects or decisions.
- LOCKED  — you explicitly told the workflow this is a hard preference.

## Aesthetic preferences
| Preference | Confidence | Evidence | Last updated |
|---|---|---|---|
<!-- e.g. | Restrained / minimal over decorative | STRONG | approved 3 minimal directions | YYYY-MM-DD | -->

## Preferred styles
<!-- Map to reference/style-taxonomy.md labels. Note when (which product types). -->

## Anti-preferences (consistently rejected)
| Avoid | Confidence | Evidence | Last updated |
|---|---|---|---|

## Defaults you tend to choose
- Type:
- Color / palette tendency:
- Spacing / density:
- Radius / shape language:
- Motion:
- Layout strategy:

## Working style with the workflow
- Question depth (fast vs thorough):
- How direct critique should be:
- Decision speed:

## Notes
<!-- Free-form durable observations. Keep entries short and dated. -->
"""


def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(2)


def profile_dir() -> Path:
    return Path.home().resolve() / ".claude" / "shavian-ui-studio"


def profile_path() -> Path:
    return profile_dir() / "taste-profile.md"


def load_seed() -> str:
    """Prefer the plugin's template seed; fall back to the embedded copy."""
    template = Path(__file__).resolve().parent.parent / "templates" / "taste-profile.md"
    if template.exists():
        try:
            return template.read_text(encoding="utf-8")
        except OSError:
            pass
    return EMBEDDED_SEED


def do_init() -> None:
    target = profile_path()
    if target.exists():
        print(f"exists: {target}")
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    seed = load_seed().rstrip() + "\n"
    target.write_text(seed, encoding="utf-8")
    print(f"created: {target}")


def do_show() -> None:
    target = profile_path()
    if not target.exists():
        print("Taste profile not found. Run with --init to create it.")
        print(f"Path would be: {target}")
        return
    print(target.read_text(encoding="utf-8"))


def main() -> None:
    parser = argparse.ArgumentParser(description="Manage the global taste profile.")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--init", action="store_true", help="Create the profile if missing. Never overwrites.")
    group.add_argument("--show", action="store_true", help="Print the profile to stdout.")
    group.add_argument("--path", action="store_true", help="Print the profile path.")
    args = parser.parse_args()

    if args.path:
        print(profile_path())
        return
    if args.show:
        do_show()
        return
    if args.init:
        do_init()
        return

    # Default: ensure it exists, then report the path.
    do_init()
    print("")
    print(f"Taste profile path: {profile_path()}")
    print("Edit this file (or let the workflow refine it) to teach your preferences.")
    print(f"Generated by Shavian UI Studio {VERSION} at {dt.datetime.now().strftime('%Y-%m-%d')}.")


if __name__ == "__main__":
    main()
